/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp5210.analysis;

import java.util.*;
import comp5210.node.*;

public class DepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(Node node)
    {
    }

    public void defaultOut(Node node)
    {
    }

    public void caseStart(Start node)
    {
        inStart(node);
        node.getPFred().apply(this);
        node.getEOF().apply(this);
        outStart(node);
    }

    public void inAPublicFred(APublicFred node)
    {
        defaultIn(node);
    }

    public void outAPublicFred(APublicFred node)
    {
        defaultOut(node);
    }

    public void caseAPublicFred(APublicFred node)
    {
        inAPublicFred(node);
        if(node.getPublic() != null)
        {
            node.getPublic().apply(this);
        }
        if(node.getId1() != null)
        {
            node.getId1().apply(this);
        }
        if(node.getId2() != null)
        {
            node.getId2().apply(this);
        }
        outAPublicFred(node);
    }

    public void inAPrivateFred(APrivateFred node)
    {
        defaultIn(node);
    }

    public void outAPrivateFred(APrivateFred node)
    {
        defaultOut(node);
    }

    public void caseAPrivateFred(APrivateFred node)
    {
        inAPrivateFred(node);
        if(node.getPrivate() != null)
        {
            node.getPrivate().apply(this);
        }
        if(node.getId1() != null)
        {
            node.getId1().apply(this);
        }
        if(node.getId2() != null)
        {
            node.getId2().apply(this);
        }
        outAPrivateFred(node);
    }
}
