/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp5210.node;

import java.util.*;
import comp5210.analysis.*;

public final class APublicFred extends PFred
{
    private TPublic _public_;
    private TId _id1_;
    private TId _id2_;

    public APublicFred()
    {
    }

    public APublicFred(
        TPublic _public_,
        TId _id1_,
        TId _id2_)
    {
        setPublic(_public_);

        setId1(_id1_);

        setId2(_id2_);

    }
    public Object clone()
    {
        return new APublicFred(
            (TPublic) cloneNode(_public_),
            (TId) cloneNode(_id1_),
            (TId) cloneNode(_id2_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPublicFred(this);
    }

    public TPublic getPublic()
    {
        return _public_;
    }

    public void setPublic(TPublic node)
    {
        if(_public_ != null)
        {
            _public_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _public_ = node;
    }

    public TId getId1()
    {
        return _id1_;
    }

    public void setId1(TId node)
    {
        if(_id1_ != null)
        {
            _id1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _id1_ = node;
    }

    public TId getId2()
    {
        return _id2_;
    }

    public void setId2(TId node)
    {
        if(_id2_ != null)
        {
            _id2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _id2_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_public_)
            + toString(_id1_)
            + toString(_id2_);
    }

    void removeChild(Node child)
    {
        if(_public_ == child)
        {
            _public_ = null;
            return;
        }

        if(_id1_ == child)
        {
            _id1_ = null;
            return;
        }

        if(_id2_ == child)
        {
            _id2_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_public_ == oldChild)
        {
            setPublic((TPublic) newChild);
            return;
        }

        if(_id1_ == oldChild)
        {
            setId1((TId) newChild);
            return;
        }

        if(_id2_ == oldChild)
        {
            setId2((TId) newChild);
            return;
        }

    }
}
