/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp5210.node;

import comp5210.analysis.*;

public final class Start extends Node
{
    private PFred _pFred_;
    private EOF _eof_;

    public Start()
    {
    }

    public Start(
        PFred _pFred_,
        EOF _eof_)
    {
        setPFred(_pFred_);
        setEOF(_eof_);
    }

    public Object clone()
    {
        return new Start(
            (PFred) cloneNode(_pFred_),
            (EOF) cloneNode(_eof_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseStart(this);
    }

    public PFred getPFred()
    {
        return _pFred_;
    }

    public void setPFred(PFred node)
    {
        if(_pFred_ != null)
        {
            _pFred_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pFred_ = node;
    }

    public EOF getEOF()
    {
        return _eof_;
    }

    public void setEOF(EOF node)
    {
        if(_eof_ != null)
        {
            _eof_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _eof_ = node;
    }

    void removeChild(Node child)
    {
        if(_pFred_ == child)
        {
            _pFred_ = null;
            return;
        }

        if(_eof_ == child)
        {
            _eof_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_pFred_ == oldChild)
        {
            setPFred((PFred) newChild);
            return;
        }

        if(_eof_ == oldChild)
        {
            setEOF((EOF) newChild);
            return;
        }
    }

    public String toString()
    {
        return "" +
            toString(_pFred_) +
            toString(_eof_);
    }
}
