/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp5210.node;

import comp5210.analysis.*;

public final class TOp extends Token
{
    public TOp(String text)
    {
        setText(text);
    }

    public TOp(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TOp(getText(), getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTOp(this);
    }
}
