/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp5210.node;

import comp5210.analysis.*;

public final class TPrivate extends Token
{
    public TPrivate()
    {
        super.setText("private");
    }

    public TPrivate(int line, int pos)
    {
        super.setText("private");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TPrivate(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPrivate(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TPrivate text.");
    }
}
