/* This file was generated by SableCC (http://www.sablecc.org/). */

using System;
using System.Collections;
using System.Text;
using System.IO;
using comp5210.node;

namespace comp5210.lexer {

internal class PushbackReader {
  private TextReader reader;
  private Stack stack = new Stack ();


  internal PushbackReader (TextReader reader)
  {
    this.reader = reader;
  }

  internal int Peek ()
  {
    if ( stack.Count > 0 ) return (int)stack.Peek();
    return reader.Peek();
  }

  internal int Read ()
  {
    if ( stack.Count > 0 ) return (int)stack.Pop();
    return reader.Read();
  }

  internal void Unread (int v)
  {
    stack.Push (v);
  }
}

public class LexerException : ApplicationException
{
    public LexerException(String message) : base (message)
    {
    }
}

public class Lexer
{
    protected Token token;
    protected State currentState = State.INITIAL;

    private PushbackReader input;
    private int line;
    private int pos;
    private bool cr;
    private bool eof;
    private StringBuilder text = new StringBuilder();

    protected virtual void Filter()
    {
    }

    public Lexer(TextReader input)
    {
        this.input = new PushbackReader(input);
    }

    public virtual Token Peek()
    {
        while(token == null)
        {
            token = GetToken();
            Filter();
        }

        return token;
    }

    public virtual Token Next()
    {
        while(token == null)
        {
            token = GetToken();
            Filter();
        }

        Token result = token;
        token = null;
        return result;
    }

    protected virtual Token GetToken()
    {
        int dfa_state = 0;

        int start_pos = pos;
        int start_line = line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        int[][][] gotoTable = Lexer.gotoTable[currentState.id()];
        int[] accept = Lexer.accept[currentState.id()];
        text.Length = 0;

        while(true)
        {
            int c = GetChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(cr)
                    {
                        cr = false;
                    }
                    else
                    {
                        line++;
                        pos = 0;
                    }
                    break;
                case 13:
                    line++;
                    pos = 0;
                    cr = true;
                    break;
                default:
                    pos++;
                    cr = false;
                    break;
                };

                text.Append((char) c);
                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.Length - 1;

                    while(low <= high)
                    {
                        int middle = (low + high) / 2;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = text.Length;
                    accept_pos = pos;
                    accept_line = line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            Token token = New0(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            Token token = New1(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            Token token = New2(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            Token token = New3(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            Token token = New4(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            Token token = New5(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            Token token = New6(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            Token token = New7(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            Token token = New8(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            Token token = New9(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            Token token = New10(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            Token token = New11(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            Token token = New12(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            Token token = New13(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            Token token = New14(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            Token token = New15(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            Token token = New16(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            Token token = New17(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            Token token = New18(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            Token token = New19(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            Token token = New20(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            Token token = New21(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            Token token = New22(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            Token token = New23(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            Token token = New24(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            Token token = New25(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            Token token = New26(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            Token token = New27(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            Token token = New28(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            Token token = New29(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            Token token = New30(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            Token token = New31(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            Token token = New32(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            Token token = New33(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            Token token = New34(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            Token token = New35(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            Token token = New36(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(text.Length > 0)
                    {
                        throw new LexerException(
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + text);
                    }
                    else
                    {
                        EOF token = new EOF(
                            start_line + 1,
                            start_pos + 1);
                        return token;
                    }
                }
            }
        }
    }

    private Token New0(String text, int line, int pos) { return new TBang(text, line, pos); }
    private Token New1(String text, int line, int pos) { return new TWhitespace(text, line, pos); }
    private Token New2(String text, int line, int pos) { return new TComment(text, line, pos); }
    private Token New3(String text, int line, int pos) { return new TClass(text, line, pos); }
    private Token New4(String text, int line, int pos) { return new TPublic(text, line, pos); }
    private Token New5(String text, int line, int pos) { return new TPrivate(text, line, pos); }
    private Token New6(String text, int line, int pos) { return new TMain(text, line, pos); }
    private Token New7(String text, int line, int pos) { return new TReturn(text, line, pos); }
    private Token New8(String text, int line, int pos) { return new TComma(text, line, pos); }
    private Token New9(String text, int line, int pos) { return new TLoop(text, line, pos); }
    private Token New10(String text, int line, int pos) { return new TIf(text, line, pos); }
    private Token New11(String text, int line, int pos) { return new TElse(text, line, pos); }
    private Token New12(String text, int line, int pos) { return new TAssignment(text, line, pos); }
    private Token New13(String text, int line, int pos) { return new TPlus(text, line, pos); }
    private Token New14(String text, int line, int pos) { return new TMinus(text, line, pos); }
    private Token New15(String text, int line, int pos) { return new TMultiplication(text, line, pos); }
    private Token New16(String text, int line, int pos) { return new TDivision(text, line, pos); }
    private Token New17(String text, int line, int pos) { return new TEqual(text, line, pos); }
    private Token New18(String text, int line, int pos) { return new TLess(text, line, pos); }
    private Token New19(String text, int line, int pos) { return new TGreater(text, line, pos); }
    private Token New20(String text, int line, int pos) { return new TLessEqual(text, line, pos); }
    private Token New21(String text, int line, int pos) { return new TGreaterEqual(text, line, pos); }
    private Token New22(String text, int line, int pos) { return new TAtLeast(text, line, pos); }
    private Token New23(String text, int line, int pos) { return new TStartParentheses(text, line, pos); }
    private Token New24(String text, int line, int pos) { return new TEndParentheses(text, line, pos); }
    private Token New25(String text, int line, int pos) { return new TStartBracket(text, line, pos); }
    private Token New26(String text, int line, int pos) { return new TEndBracket(text, line, pos); }
    private Token New27(String text, int line, int pos) { return new TStartBrace(text, line, pos); }
    private Token New28(String text, int line, int pos) { return new TEndBrace(text, line, pos); }
    private Token New29(String text, int line, int pos) { return new TEnd(text, line, pos); }
    private Token New30(String text, int line, int pos) { return new TAnd(text, line, pos); }
    private Token New31(String text, int line, int pos) { return new TOr(text, line, pos); }
    private Token New32(String text, int line, int pos) { return new TNot(text, line, pos); }
    private Token New33(String text, int line, int pos) { return new TFloat(text, line, pos); }
    private Token New34(String text, int line, int pos) { return new TInteger(text, line, pos); }
    private Token New35(String text, int line, int pos) { return new TVariable(text, line, pos); }
    private Token New36(String text, int line, int pos) { return new TString(text, line, pos); }

    private int GetChar()
    {
        if(eof)
        {
            return -1;
        }

        int result = input.Read();

        if(result == -1)
        {
            eof = true;
        }

        return result;
    }

    private void PushBack(int acceptLength)
    {
        int length = text.Length;
        for(int i = length - 1; i >= acceptLength; i--)
        {
            eof = false;

            input.Unread(text[i]);
        }
    }


    protected virtual void Unread(Token token)
    {
        String text = token.Text;
        int length = text.Length;

        for(int i = length - 1; i >= 0; i--)
        {
            eof = false;

            input.Unread(text[i]);
        }

        pos = token.Pos - 1;
        line = token.Line - 1;
    }

    private string GetText(int acceptLength)
    {
        StringBuilder s = new StringBuilder(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.Append(text[i]);
        }

        return s.ToString();
    }

    private static int[][][][] gotoTable = {
      new int[][][] {
        new int[][] {
          new int[] {9, 9, 1},
          new int[] {10, 10, 2},
          new int[] {13, 13, 3},
          new int[] {32, 32, 4},
          new int[] {33, 33, 5},
          new int[] {34, 34, 6},
          new int[] {44, 44, 7},
          new int[] {48, 57, 8},
          new int[] {65, 90, 9},
          new int[] {97, 97, 10},
          new int[] {98, 98, 9},
          new int[] {99, 99, 11},
          new int[] {100, 100, 12},
          new int[] {101, 101, 13},
          new int[] {102, 104, 9},
          new int[] {105, 105, 14},
          new int[] {106, 107, 9},
          new int[] {108, 108, 15},
          new int[] {109, 109, 16},
          new int[] {110, 110, 17},
          new int[] {111, 111, 18},
          new int[] {112, 112, 19},
          new int[] {113, 113, 9},
          new int[] {114, 114, 20},
          new int[] {115, 115, 21},
          new int[] {116, 116, 22},
          new int[] {117, 122, 9},
        },
        new int[][] {
          new int[] {9, 32, -2},
        },
        new int[][] {
          new int[] {9, 32, -2},
        },
        new int[][] {
          new int[] {9, 32, -2},
        },
        new int[][] {
          new int[] {9, 32, -2},
        },
        new int[][] {
        },
        new int[][] {
          new int[] {32, 32, 23},
          new int[] {33, 33, 24},
          new int[] {34, 34, 25},
          new int[] {35, 46, 26},
          new int[] {47, 47, 27},
          new int[] {48, 127, 26},
        },
        new int[][] {
        },
        new int[][] {
          new int[] {46, 46, 28},
          new int[] {48, 57, 8},
        },
        new int[][] {
          new int[] {48, 57, 29},
          new int[] {65, 90, 30},
          new int[] {97, 122, 30},
        },
        new int[][] {
          new int[] {48, 90, -11},
          new int[] {97, 109, 30},
          new int[] {110, 110, 31},
          new int[] {111, 122, 30},
        },
        new int[][] {
          new int[] {48, 90, -11},
          new int[] {97, 107, 30},
          new int[] {108, 108, 32},
          new int[] {109, 110, 30},
          new int[] {111, 111, 33},
          new int[] {112, 122, 30},
        },
        new int[][] {
          new int[] {48, 90, -11},
          new int[] {97, 104, 30},
          new int[] {105, 105, 34},
          new int[] {106, 122, 30},
        },
        new int[][] {
          new int[] {48, 107, -13},
          new int[] {108, 108, 35},
          new int[] {109, 109, 30},
          new int[] {110, 110, 36},
          new int[] {111, 112, 30},
          new int[] {113, 113, 37},
          new int[] {114, 122, 30},
        },
        new int[][] {
          new int[] {48, 90, -11},
          new int[] {97, 101, 30},
          new int[] {102, 102, 38},
          new int[] {103, 114, 30},
          new int[] {115, 115, 39},
          new int[] {116, 122, 30},
        },
        new int[][] {
          new int[] {48, 90, -11},
          new int[] {97, 110, 30},
          new int[] {111, 111, 40},
          new int[] {112, 122, 30},
        },
        new int[][] {
          new int[] {48, 90, -11},
          new int[] {97, 97, 41},
          new int[] {98, 104, 30},
          new int[] {105, 105, 42},
          new int[] {106, 122, 30},
        },
        new int[][] {
          new int[] {48, 110, -17},
          new int[] {111, 111, 43},
          new int[] {112, 122, 30},
        },
        new int[][] {
          new int[] {48, 90, -11},
          new int[] {97, 113, 30},
          new int[] {114, 114, 44},
          new int[] {115, 122, 30},
        },
        new int[][] {
          new int[] {48, 107, -13},
          new int[] {108, 108, 45},
          new int[] {109, 113, 30},
          new int[] {114, 114, 46},
          new int[] {115, 116, 30},
          new int[] {117, 117, 47},
          new int[] {118, 122, 30},
        },
        new int[][] {
          new int[] {48, 90, -11},
          new int[] {97, 100, 30},
          new int[] {101, 101, 48},
          new int[] {102, 122, 30},
        },
        new int[][] {
          new int[] {48, 90, -11},
          new int[] {97, 115, 30},
          new int[] {116, 116, 49},
          new int[] {117, 122, 30},
        },
        new int[][] {
          new int[] {48, 104, -14},
          new int[] {105, 105, 50},
          new int[] {106, 122, 30},
        },
        new int[][] {
          new int[] {32, 127, -8},
        },
        new int[][] {
          new int[] {32, 127, -8},
        },
        new int[][] {
        },
        new int[][] {
          new int[] {32, 127, -8},
        },
        new int[][] {
          new int[] {32, 33, -8},
          new int[] {34, 34, 51},
          new int[] {35, 127, -8},
        },
        new int[][] {
          new int[] {48, 57, 52},
        },
        new int[][] {
          new int[] {48, 57, 29},
          new int[] {65, 90, 53},
          new int[] {95, 95, 54},
          new int[] {97, 122, 53},
        },
        new int[][] {
          new int[] {48, 90, -11},
          new int[] {95, 95, 55},
          new int[] {97, 122, 30},
        },
        new int[][] {
          new int[] {48, 95, -32},
          new int[] {97, 99, 30},
          new int[] {100, 100, 56},
          new int[] {101, 122, 30},
        },
        new int[][] {
          new int[] {48, 95, -32},
          new int[] {97, 97, 57},
          new int[] {98, 122, 30},
        },
        new int[][] {
          new int[] {48, 95, -32},
          new int[] {97, 108, 30},
          new int[] {109, 109, 58},
          new int[] {110, 122, 30},
        },
        new int[][] {
          new int[] {48, 95, -32},
          new int[] {97, 117, 30},
          new int[] {118, 118, 59},
          new int[] {119, 122, 30},
        },
        new int[][] {
          new int[] {48, 95, -32},
          new int[] {97, 114, 30},
          new int[] {115, 115, 60},
          new int[] {116, 122, 30},
        },
        new int[][] {
          new int[] {48, 99, -33},
          new int[] {100, 100, 61},
          new int[] {101, 122, 30},
        },
        new int[][] {
          new int[] {48, 95, -32},
          new int[] {97, 116, 30},
          new int[] {117, 117, 62},
          new int[] {118, 122, 30},
        },
        new int[][] {
          new int[] {48, 122, -32},
        },
        new int[][] {
          new int[] {32, 32, 63},
          new int[] {48, 122, -32},
        },
        new int[][] {
          new int[] {48, 95, -32},
          new int[] {97, 110, 30},
          new int[] {111, 111, 64},
          new int[] {112, 122, 30},
        },
        new int[][] {
          new int[] {48, 95, -32},
          new int[] {97, 104, 30},
          new int[] {105, 105, 65},
          new int[] {106, 122, 30},
        },
        new int[][] {
          new int[] {48, 95, -32},
          new int[] {97, 109, 30},
          new int[] {110, 110, 66},
          new int[] {111, 122, 30},
        },
        new int[][] {
          new int[] {48, 95, -32},
          new int[] {97, 115, 30},
          new int[] {116, 116, 67},
          new int[] {117, 122, 30},
        },
        new int[][] {
          new int[] {48, 122, -32},
        },
        new int[][] {
          new int[] {48, 116, -39},
          new int[] {117, 117, 68},
          new int[] {118, 122, 30},
        },
        new int[][] {
          new int[] {48, 104, -43},
          new int[] {105, 105, 69},
          new int[] {106, 122, 30},
        },
        new int[][] {
          new int[] {48, 95, -32},
          new int[] {97, 97, 30},
          new int[] {98, 98, 70},
          new int[] {99, 122, 30},
        },
        new int[][] {
          new int[] {48, 115, -45},
          new int[] {116, 116, 71},
          new int[] {117, 122, 30},
        },
        new int[][] {
          new int[] {48, 95, -32},
          new int[] {97, 97, 72},
          new int[] {98, 122, 30},
        },
        new int[][] {
          new int[] {48, 108, -35},
          new int[] {109, 109, 73},
          new int[] {110, 122, 30},
        },
        new int[][] {
          new int[] {32, 127, -8},
        },
        new int[][] {
          new int[] {48, 57, 52},
          new int[] {101, 101, 74},
        },
        new int[][] {
          new int[] {48, 90, -31},
          new int[] {95, 95, 55},
          new int[] {97, 122, 53},
        },
        new int[][] {
          new int[] {48, 90, -31},
          new int[] {97, 122, 53},
        },
        new int[][] {
          new int[] {48, 122, -56},
        },
        new int[][] {
          new int[] {48, 122, -32},
        },
        new int[][] {
          new int[] {48, 114, -37},
          new int[] {115, 115, 75},
          new int[] {116, 122, 30},
        },
        new int[][] {
          new int[] {48, 108, -35},
          new int[] {109, 109, 76},
          new int[] {110, 122, 30},
        },
        new int[][] {
          new int[] {48, 104, -43},
          new int[] {105, 105, 77},
          new int[] {106, 122, 30},
        },
        new int[][] {
          new int[] {48, 95, -32},
          new int[] {97, 100, 30},
          new int[] {101, 101, 78},
          new int[] {102, 122, 30},
        },
        new int[][] {
          new int[] {32, 32, 79},
          new int[] {48, 122, -32},
        },
        new int[][] {
          new int[] {48, 95, -32},
          new int[] {97, 97, 80},
          new int[] {98, 122, 30},
        },
        new int[][] {
          new int[] {97, 97, 81},
          new int[] {103, 103, 82},
          new int[] {108, 108, 83},
        },
        new int[][] {
          new int[] {48, 95, -32},
          new int[] {97, 111, 30},
          new int[] {112, 112, 84},
          new int[] {113, 122, 30},
        },
        new int[][] {
          new int[] {48, 109, -44},
          new int[] {110, 110, 85},
          new int[] {111, 122, 30},
        },
        new int[][] {
          new int[] {48, 116, -39},
          new int[] {117, 117, 86},
          new int[] {118, 122, 30},
        },
        new int[][] {
          new int[] {48, 122, -32},
        },
        new int[][] {
          new int[] {48, 114, -37},
          new int[] {115, 115, 87},
          new int[] {116, 122, 30},
        },
        new int[][] {
          new int[] {48, 117, -36},
          new int[] {118, 118, 88},
          new int[] {119, 122, 30},
        },
        new int[][] {
          new int[] {48, 95, -32},
          new int[] {97, 107, 30},
          new int[] {108, 108, 89},
          new int[] {109, 122, 30},
        },
        new int[][] {
          new int[] {48, 116, -39},
          new int[] {117, 117, 90},
          new int[] {118, 122, 30},
        },
        new int[][] {
          new int[] {48, 95, -32},
          new int[] {97, 113, 30},
          new int[] {114, 114, 91},
          new int[] {115, 122, 30},
        },
        new int[][] {
          new int[] {48, 100, -62},
          new int[] {101, 101, 92},
          new int[] {102, 122, 30},
        },
        new int[][] {
          new int[] {45, 45, 93},
          new int[] {48, 57, 94},
        },
        new int[][] {
          new int[] {48, 114, -37},
          new int[] {115, 115, 95},
          new int[] {116, 122, 30},
        },
        new int[][] {
          new int[] {48, 100, -62},
          new int[] {101, 101, 96},
          new int[] {102, 122, 30},
        },
        new int[][] {
          new int[] {48, 99, -33},
          new int[] {100, 100, 97},
          new int[] {101, 122, 30},
        },
        new int[][] {
          new int[] {48, 122, -32},
        },
        new int[][] {
          new int[] {98, 98, 98},
          new int[] {112, 112, 99},
        },
        new int[][] {
          new int[] {48, 107, -72},
          new int[] {108, 108, 100},
          new int[] {109, 122, 30},
        },
        new int[][] {
          new int[] {115, 115, 101},
          new int[] {116, 116, 102},
        },
        new int[][] {
          new int[] {114, 114, 103},
        },
        new int[][] {
          new int[] {101, 101, 104},
        },
        new int[][] {
          new int[] {48, 122, -32},
        },
        new int[][] {
          new int[] {48, 122, -32},
        },
        new int[][] {
          new int[] {48, 114, -37},
          new int[] {115, 115, 105},
          new int[] {116, 122, 30},
        },
        new int[][] {
          new int[] {48, 122, -32},
        },
        new int[][] {
          new int[] {48, 95, -32},
          new int[] {97, 97, 106},
          new int[] {98, 122, 30},
        },
        new int[][] {
          new int[] {48, 104, -43},
          new int[] {105, 105, 107},
          new int[] {106, 122, 30},
        },
        new int[][] {
          new int[] {48, 113, -74},
          new int[] {114, 114, 108},
          new int[] {115, 122, 30},
        },
        new int[][] {
          new int[] {48, 115, -45},
          new int[] {116, 116, 109},
          new int[] {117, 122, 30},
        },
        new int[][] {
          new int[] {48, 114, -37},
          new int[] {115, 115, 110},
          new int[] {116, 122, 30},
        },
        new int[][] {
          new int[] {48, 57, 94},
        },
        new int[][] {
          new int[] {48, 57, 94},
        },
        new int[][] {
          new int[] {48, 122, -32},
        },
        new int[][] {
          new int[] {48, 109, -44},
          new int[] {110, 110, 111},
          new int[] {111, 122, 30},
        },
        new int[][] {
          new int[] {48, 100, -62},
          new int[] {101, 101, 112},
          new int[] {102, 122, 30},
        },
        new int[][] {
          new int[] {114, 114, 113},
        },
        new int[][] {
          new int[] {97, 97, 114},
        },
        new int[][] {
          new int[] {48, 114, -37},
          new int[] {115, 115, 115},
          new int[] {116, 122, 30},
        },
        new int[][] {
          new int[] {115, 115, 116},
        },
        new int[][] {
          new int[] {32, 32, 117},
        },
        new int[][] {
          new int[] {101, 101, 118},
        },
        new int[][] {
          new int[] {115, 115, 119},
        },
        new int[][] {
          new int[] {48, 122, -32},
        },
        new int[][] {
          new int[] {48, 115, -45},
          new int[] {116, 116, 120},
          new int[] {117, 122, 30},
        },
        new int[][] {
          new int[] {48, 95, -32},
          new int[] {97, 98, 30},
          new int[] {99, 99, 121},
          new int[] {100, 122, 30},
        },
        new int[][] {
          new int[] {48, 109, -44},
          new int[] {110, 110, 122},
          new int[] {111, 122, 30},
        },
        new int[][] {
          new int[] {32, 32, 123},
          new int[] {48, 122, -32},
        },
        new int[][] {
          new int[] {48, 122, -32},
        },
        new int[][] {
          new int[] {48, 115, -45},
          new int[] {116, 116, 124},
          new int[] {117, 122, 30},
        },
        new int[][] {
          new int[] {48, 99, -33},
          new int[] {100, 100, 125},
          new int[] {101, 122, 30},
        },
        new int[][] {
          new int[] {97, 97, 126},
        },
        new int[][] {
          new int[] {114, 114, 127},
        },
        new int[][] {
          new int[] {48, 122, -32},
        },
        new int[][] {
          new int[] {105, 105, 128},
        },
        new int[][] {
          new int[] {108, 108, 129},
        },
        new int[][] {
          new int[] {97, 97, 130},
        },
        new int[][] {
          new int[] {115, 115, 131},
        },
        new int[][] {
          new int[] {48, 100, -62},
          new int[] {101, 101, 132},
          new int[] {102, 122, 30},
        },
        new int[][] {
          new int[] {48, 122, -32},
        },
        new int[][] {
          new int[] {48, 122, -32},
        },
        new int[][] {
          new int[] {98, 98, 133},
          new int[] {112, 112, 134},
        },
        new int[][] {
          new int[] {10, 10, 135},
          new int[] {13, 13, 136},
          new int[] {32, 47, 137},
          new int[] {48, 57, 138},
          new int[] {58, 64, 137},
          new int[] {65, 90, 139},
          new int[] {91, 94, 137},
          new int[] {95, 95, 140},
          new int[] {96, 96, 137},
          new int[] {97, 122, 139},
          new int[] {123, 127, 137},
        },
        new int[][] {
          new int[] {32, 32, 141},
          new int[] {48, 122, -32},
        },
        new int[][] {
          new int[] {99, 99, 142},
        },
        new int[][] {
          new int[] {101, 101, 143},
        },
        new int[][] {
          new int[] {103, 103, 144},
        },
        new int[][] {
          new int[] {101, 101, 145},
        },
        new int[][] {
          new int[] {116, 116, 146},
        },
        new int[][] {
          new int[] {32, 32, 147},
        },
        new int[][] {
          new int[] {48, 122, -32},
        },
        new int[][] {
          new int[] {114, 114, 148},
        },
        new int[][] {
          new int[] {97, 97, 149},
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
          new int[] {10, 47, -126},
          new int[] {48, 57, 150},
          new int[] {58, 127, 137},
        },
        new int[][] {
          new int[] {10, 64, -126},
          new int[] {65, 90, 151},
          new int[] {91, 94, 137},
          new int[] {95, 95, 152},
          new int[] {96, 96, 137},
          new int[] {97, 122, 151},
          new int[] {123, 127, 137},
        },
        new int[][] {
          new int[] {10, 127, -126},
        },
        new int[][] {
          new int[] {10, 90, -140},
          new int[] {91, 96, 137},
          new int[] {97, 127, -140},
        },
        new int[][] {
          new int[] {98, 98, 153},
        },
        new int[][] {
          new int[] {101, 101, 154},
          new int[] {107, 107, 155},
        },
        new int[][] {
          new int[] {110, 110, 156},
        },
        new int[][] {
          new int[] {110, 110, 157},
        },
        new int[][] {
          new int[] {97, 97, 158},
        },
        new int[][] {
          new int[] {101, 101, 159},
        },
        new int[][] {
          new int[] {116, 116, 160},
        },
        new int[][] {
          new int[] {97, 97, 161},
        },
        new int[][] {
          new int[] {114, 114, 162},
        },
        new int[][] {
          new int[] {10, 127, -139},
        },
        new int[][] {
          new int[] {10, 94, -140},
          new int[] {95, 96, -126},
          new int[] {97, 127, -140},
        },
        new int[][] {
          new int[] {10, 127, -142},
        },
        new int[][] {
          new int[] {121, 121, 163},
        },
        new int[][] {
        },
        new int[][] {
          new int[] {101, 101, 164},
        },
        new int[][] {
          new int[] {116, 116, 165},
        },
        new int[][] {
          new int[] {101, 101, 166},
        },
        new int[][] {
          new int[] {115, 115, 167},
        },
        new int[][] {
          new int[] {114, 114, 168},
        },
        new int[][] {
          new int[] {104, 104, 169},
        },
        new int[][] {
          new int[] {99, 99, 170},
        },
        new int[][] {
          new int[] {101, 101, 171},
        },
        new int[][] {
        },
        new int[][] {
          new int[] {116, 116, 172},
        },
        new int[][] {
          new int[] {104, 104, 173},
        },
        new int[][] {
          new int[] {100, 100, 174},
        },
        new int[][] {
          new int[] {116, 116, 175},
        },
        new int[][] {
          new int[] {32, 32, 176},
        },
        new int[][] {
          new int[] {97, 97, 177},
        },
        new int[][] {
          new int[] {101, 101, 178},
          new int[] {107, 107, 179},
        },
        new int[][] {
          new int[] {110, 110, 180},
        },
        new int[][] {
        },
        new int[][] {
          new int[] {101, 101, 181},
        },
        new int[][] {
          new int[] {32, 32, 182},
        },
        new int[][] {
        },
        new int[][] {
          new int[] {116, 116, 183},
        },
        new int[][] {
          new int[] {110, 110, 184},
        },
        new int[][] {
        },
        new int[][] {
          new int[] {101, 101, 185},
        },
        new int[][] {
          new int[] {116, 116, 186},
        },
        new int[][] {
          new int[] {115, 115, 187},
        },
        new int[][] {
          new int[] {116, 116, 188},
        },
        new int[][] {
          new int[] {104, 104, 189},
        },
        new int[][] {
          new int[] {32, 32, 190},
        },
        new int[][] {
          new int[] {116, 116, 191},
        },
        new int[][] {
          new int[] {104, 104, 192},
        },
        new int[][] {
          new int[] {101, 101, 193},
        },
        new int[][] {
          new int[] {111, 111, 194},
        },
        new int[][] {
          new int[] {97, 97, 195},
        },
        new int[][] {
          new int[] {111, 111, 196},
        },
        new int[][] {
        },
        new int[][] {
          new int[] {101, 101, 197},
        },
        new int[][] {
          new int[] {115, 115, 198},
        },
        new int[][] {
        },
        new int[][] {
          new int[] {110, 110, 199},
        },
        new int[][] {
          new int[] {114, 114, 200},
        },
        new int[][] {
          new int[] {115, 115, 201},
        },
        new int[][] {
        },
        new int[][] {
          new int[] {32, 32, 202},
        },
        new int[][] {
          new int[] {32, 32, 203},
        },
        new int[][] {
          new int[] {101, 101, 204},
        },
        new int[][] {
          new int[] {111, 111, 205},
        },
        new int[][] {
          new int[] {101, 101, 206},
        },
        new int[][] {
          new int[] {115, 115, 207},
        },
        new int[][] {
          new int[] {114, 114, 208},
        },
        new int[][] {
          new int[] {113, 113, 209},
        },
        new int[][] {
        },
        new int[][] {
          new int[] {32, 32, 210},
        },
        new int[][] {
          new int[] {117, 117, 211},
        },
        new int[][] {
          new int[] {101, 101, 212},
        },
        new int[][] {
          new int[] {97, 97, 213},
        },
        new int[][] {
          new int[] {113, 113, 214},
        },
        new int[][] {
          new int[] {108, 108, 215},
        },
        new int[][] {
          new int[] {117, 117, 216},
        },
        new int[][] {
          new int[] {32, 32, 217},
        },
        new int[][] {
          new int[] {97, 97, 218},
        },
        new int[][] {
          new int[] {116, 116, 219},
        },
        new int[][] {
          new int[] {108, 108, 220},
        },
        new int[][] {
          new int[] {111, 111, 221},
        },
        new int[][] {
          new int[] {32, 32, 222},
        },
        new int[][] {
        },
        new int[][] {
          new int[] {116, 116, 223},
        },
        new int[][] {
          new int[] {111, 111, 224},
        },
        new int[][] {
        },
      },
    };

    private static int[][] accept = {
      new int[] {
        -1, 1, 1, 1, 1, 0, -1, 8, 34, 35, 35, 35, 35, 35, 35, 35, 
        35, 35, 35, 35, 35, 35, 35, -1, -1, 36, -1, -1, -1, 35, 35, 35, 
        35, 35, 35, 35, 35, 35, 10, 35, 35, 35, 35, 35, 31, 35, 35, 35, 
        35, 35, 35, 36, -1, 35, 35, 35, 30, 35, 35, 35, 35, 29, 35, -1, 
        35, 35, 35, 32, 35, 35, 35, 35, 35, 35, -1, 35, 35, 35, 11, -1, 
        35, -1, -1, -1, 9, 6, 35, 13, 35, 35, 35, 35, 35, -1, 33, 3, 
        35, 35, -1, -1, 35, -1, -1, -1, -1, 14, 35, 35, 35, 35, 15, 35, 
        35, -1, -1, 17, -1, -1, -1, -1, 35, 4, 7, -1, 35, 35, -1, -1, 
        -1, -1, -1, -1, 5, -1, -1, 2, 2, -1, 35, 35, 35, -1, -1, -1, 
        -1, -1, -1, -1, -1, -1, -1, 35, 35, -1, 28, -1, -1, -1, -1, -1, 
        -1, -1, -1, 16, -1, -1, -1, -1, -1, -1, -1, -1, 26, -1, -1, 22, 
        -1, -1, 27, -1, -1, -1, -1, -1, 18, -1, -1, -1, -1, -1, -1, 25, 
        -1, -1, 12, -1, -1, -1, 24, 19, -1, -1, -1, -1, -1, -1, -1, 23, 
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 20, -1, -1, 
        21, 
      },
    };

    public class State
    {
        public static State INITIAL = new State(0);

        private int _id;

        private State(int _id)
        {
            this._id = _id;
        }

        public int id()
        {
            return _id;
        }
    }
}
}
