/* This file was generated by SableCC (http://www.sablecc.org/). */

using System;
using System.Collections;
using System.Text;
using System.IO;
using comp5210.node;

namespace comp5210.lexer {

internal class PushbackReader {
  private TextReader reader;
  private Stack stack = new Stack ();


  internal PushbackReader (TextReader reader)
  {
    this.reader = reader;
  }

  internal int Peek ()
  {
    if ( stack.Count > 0 ) return (int)stack.Peek();
    return reader.Peek();
  }

  internal int Read ()
  {
    if ( stack.Count > 0 ) return (int)stack.Pop();
    return reader.Read();
  }

  internal void Unread (int v)
  {
    stack.Push (v);
  }
}

public class LexerException : ApplicationException
{
    public LexerException(String message) : base (message)
    {
    }
}

public class Lexer
{
    protected Token token;
    protected State currentState = State.INITIAL;

    private PushbackReader input;
    private int line;
    private int pos;
    private bool cr;
    private bool eof;
    private StringBuilder text = new StringBuilder();

    protected virtual void Filter()
    {
    }

    public Lexer(TextReader input)
    {
        this.input = new PushbackReader(input);
    }

    public virtual Token Peek()
    {
        while(token == null)
        {
            token = GetToken();
            Filter();
        }

        return token;
    }

    public virtual Token Next()
    {
        while(token == null)
        {
            token = GetToken();
            Filter();
        }

        Token result = token;
        token = null;
        return result;
    }

    protected virtual Token GetToken()
    {
        int dfa_state = 0;

        int start_pos = pos;
        int start_line = line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        int[][][] gotoTable = Lexer.gotoTable[currentState.id()];
        int[] accept = Lexer.accept[currentState.id()];
        text.Length = 0;

        while(true)
        {
            int c = GetChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(cr)
                    {
                        cr = false;
                    }
                    else
                    {
                        line++;
                        pos = 0;
                    }
                    break;
                case 13:
                    line++;
                    pos = 0;
                    cr = true;
                    break;
                default:
                    pos++;
                    cr = false;
                    break;
                };

                text.Append((char) c);
                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.Length - 1;

                    while(low <= high)
                    {
                        int middle = (low + high) / 2;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = text.Length;
                    accept_pos = pos;
                    accept_line = line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            Token token = New0(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            Token token = New1(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            Token token = New2(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            Token token = New3(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            Token token = New4(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            Token token = New5(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            Token token = New6(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            Token token = New7(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            Token token = New8(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(text.Length > 0)
                    {
                        throw new LexerException(
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + text);
                    }
                    else
                    {
                        EOF token = new EOF(
                            start_line + 1,
                            start_pos + 1);
                        return token;
                    }
                }
            }
        }
    }

    private Token New0(String text, int line, int pos) { return new TBang(text, line, pos); }
    private Token New1(String text, int line, int pos) { return new TWhitespace(text, line, pos); }
    private Token New2(String text, int line, int pos) { return new TComment(text, line, pos); }
    private Token New3(String text, int line, int pos) { return new TOp(text, line, pos); }
    private Token New4(String text, int line, int pos) { return new TClass(text, line, pos); }
    private Token New5(String text, int line, int pos) { return new TPublic(text, line, pos); }
    private Token New6(String text, int line, int pos) { return new TPrivate(text, line, pos); }
    private Token New7(String text, int line, int pos) { return new TId(text, line, pos); }
    private Token New8(String text, int line, int pos) { return new TReturn(text, line, pos); }

    private int GetChar()
    {
        if(eof)
        {
            return -1;
        }

        int result = input.Read();

        if(result == -1)
        {
            eof = true;
        }

        return result;
    }

    private void PushBack(int acceptLength)
    {
        int length = text.Length;
        for(int i = length - 1; i >= acceptLength; i--)
        {
            eof = false;

            input.Unread(text[i]);
        }
    }


    protected virtual void Unread(Token token)
    {
        String text = token.Text;
        int length = text.Length;

        for(int i = length - 1; i >= 0; i--)
        {
            eof = false;

            input.Unread(text[i]);
        }

        pos = token.Pos - 1;
        line = token.Line - 1;
    }

    private string GetText(int acceptLength)
    {
        StringBuilder s = new StringBuilder(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.Append(text[i]);
        }

        return s.ToString();
    }

    private static int[][][][] gotoTable = {
      new int[][][] {
        new int[][] {
          new int[] {9, 9, 1},
          new int[] {10, 10, 2},
          new int[] {13, 13, 3},
          new int[] {32, 32, 4},
          new int[] {33, 33, 5},
          new int[] {38, 38, 6},
          new int[] {42, 42, 7},
          new int[] {43, 43, 8},
          new int[] {45, 45, 9},
          new int[] {47, 47, 10},
          new int[] {60, 60, 11},
          new int[] {65, 90, 12},
          new int[] {97, 98, 12},
          new int[] {99, 99, 13},
          new int[] {100, 111, 12},
          new int[] {112, 112, 14},
          new int[] {113, 113, 12},
          new int[] {114, 114, 15},
          new int[] {115, 122, 12},
        },
        new int[][] {
          new int[] {9, 32, -2},
        },
        new int[][] {
          new int[] {9, 32, -2},
        },
        new int[][] {
          new int[] {9, 32, -2},
        },
        new int[][] {
          new int[] {9, 32, -2},
        },
        new int[][] {
        },
        new int[][] {
          new int[] {38, 38, 16},
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
          new int[] {42, 42, 17},
          new int[] {47, 47, 18},
        },
        new int[][] {
        },
        new int[][] {
          new int[] {65, 90, 12},
          new int[] {97, 122, 12},
        },
        new int[][] {
          new int[] {65, 90, 12},
          new int[] {97, 107, 12},
          new int[] {108, 108, 19},
          new int[] {109, 122, 12},
        },
        new int[][] {
          new int[] {65, 90, 12},
          new int[] {97, 113, 12},
          new int[] {114, 114, 20},
          new int[] {115, 116, 12},
          new int[] {117, 117, 21},
          new int[] {118, 122, 12},
        },
        new int[][] {
          new int[] {65, 90, 12},
          new int[] {97, 100, 12},
          new int[] {101, 101, 22},
          new int[] {102, 122, 12},
        },
        new int[][] {
        },
        new int[][] {
          new int[] {32, 41, 23},
          new int[] {42, 42, 24},
          new int[] {43, 127, 23},
        },
        new int[][] {
          new int[] {10, 10, 25},
          new int[] {13, 13, 26},
          new int[] {32, 127, 27},
        },
        new int[][] {
          new int[] {65, 90, 12},
          new int[] {97, 97, 28},
          new int[] {98, 122, 12},
        },
        new int[][] {
          new int[] {65, 90, 12},
          new int[] {97, 104, 12},
          new int[] {105, 105, 29},
          new int[] {106, 122, 12},
        },
        new int[][] {
          new int[] {65, 90, 12},
          new int[] {97, 97, 12},
          new int[] {98, 98, 30},
          new int[] {99, 122, 12},
        },
        new int[][] {
          new int[] {65, 90, 12},
          new int[] {97, 115, 12},
          new int[] {116, 116, 31},
          new int[] {117, 122, 12},
        },
        new int[][] {
          new int[] {32, 127, -19},
        },
        new int[][] {
          new int[] {32, 42, -19},
          new int[] {43, 46, 23},
          new int[] {47, 47, 32},
          new int[] {48, 127, 23},
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
          new int[] {10, 127, -20},
        },
        new int[][] {
          new int[] {65, 90, 12},
          new int[] {97, 114, 12},
          new int[] {115, 115, 33},
          new int[] {116, 122, 12},
        },
        new int[][] {
          new int[] {65, 90, 12},
          new int[] {97, 117, 12},
          new int[] {118, 118, 34},
          new int[] {119, 122, 12},
        },
        new int[][] {
          new int[] {65, 107, -15},
          new int[] {108, 108, 35},
          new int[] {109, 122, 12},
        },
        new int[][] {
          new int[] {65, 90, 12},
          new int[] {97, 116, 12},
          new int[] {117, 117, 36},
          new int[] {118, 122, 12},
        },
        new int[][] {
          new int[] {32, 127, -19},
        },
        new int[][] {
          new int[] {65, 114, -30},
          new int[] {115, 115, 37},
          new int[] {116, 122, 12},
        },
        new int[][] {
          new int[] {65, 90, 12},
          new int[] {97, 97, 38},
          new int[] {98, 122, 12},
        },
        new int[][] {
          new int[] {65, 104, -22},
          new int[] {105, 105, 39},
          new int[] {106, 122, 12},
        },
        new int[][] {
          new int[] {65, 113, -16},
          new int[] {114, 114, 40},
          new int[] {115, 122, 12},
        },
        new int[][] {
          new int[] {65, 122, -14},
        },
        new int[][] {
          new int[] {65, 115, -24},
          new int[] {116, 116, 41},
          new int[] {117, 122, 12},
        },
        new int[][] {
          new int[] {65, 98, -2},
          new int[] {99, 99, 42},
          new int[] {100, 122, 12},
        },
        new int[][] {
          new int[] {65, 90, 12},
          new int[] {97, 109, 12},
          new int[] {110, 110, 43},
          new int[] {111, 122, 12},
        },
        new int[][] {
          new int[] {65, 100, -17},
          new int[] {101, 101, 44},
          new int[] {102, 122, 12},
        },
        new int[][] {
          new int[] {65, 122, -14},
        },
        new int[][] {
          new int[] {65, 122, -14},
        },
        new int[][] {
          new int[] {65, 122, -14},
        },
      },
    };

    private static int[][] accept = {
      new int[] {
        -1, 1, 1, 1, 1, 0, -1, 3, 3, 3, -1, 3, 7, 7, 7, 7, 
        3, -1, -1, 7, 7, 7, 7, -1, -1, 2, 2, -1, 7, 7, 7, 7, 
        2, 7, 7, 7, 7, 4, 7, 7, 7, 7, 5, 7, 6, 
      },
    };

    public class State
    {
        public static State INITIAL = new State(0);

        private int _id;

        private State(int _id)
        {
            this._id = _id;
        }

        public int id()
        {
            return _id;
        }
    }
}
}
