/* This file was generated by SableCC (http://www.sablecc.org/). */

package comp5210.parser;

import comp5210.node.*;
import comp5210.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    public void caseTBang(TBang node)
    {
        index = 0;
    }

    public void caseTOp(TOp node)
    {
        index = 1;
    }

    public void caseTClass(TClass node)
    {
        index = 2;
    }

    public void caseTPublic(TPublic node)
    {
        index = 3;
    }

    public void caseTPrivate(TPrivate node)
    {
        index = 4;
    }

    public void caseTId(TId node)
    {
        index = 5;
    }

    public void caseTReturn(TReturn node)
    {
        index = 6;
    }

    public void caseEOF(EOF node)
    {
        index = 7;
    }
}
